# server
# version: 1.0.2

# 框架配置
codframe:
  # 启动ip
  # 可不填
  #host: 127.0.0.1
  # 启动端口
  # 不填默认9999
  # port: 8081
  # web.xml路径; 默认不需要修改
  web: classpath*:webapp/WEB-INF/web.xml
  webapp: cod-action/src/main/webapp/
  # 上线目录
  # webapp: webapp/
  # 项目头名
  project: /

# 日志配置
log:
  # 日志支持的类型 clog(默认), slf4j, logback, aliyunLog
  # 有配置文件使用配置文件没有使用数据库在没有默认clog
  type: log4j
  # 路径必须以 /  结尾
  href: .cod-temp/codLog/
  # 按日期拆文件夹 不设置默认 yyyy/MM/dd 格式
  pattern: yyyy/MM/dd
  # 是否按日志级别拆分文件夹
  # 不是必填; 默认不拆
  split: true
  # 单个日志文件大小
  size: 10M
  # 日志等级 debug < info < warn < error < fatal
  level: info
  # 是否打印控制台日志
  console: true

# 缓存设置
cache:
  # 缓存类型 支持: codCacheMemcached, codCacheEhcache(默认), codCacheJson, codCacheRedis, codCacheDatabase, codCacheFile
  type: codCacheEhcache
  # 是否开启缓存
  # 开启: 1/true; 关闭: 0/false;
  isOpen: 1
  # 全局缓存
  # 开启: 1/true; 关闭: 0/false;
  isGlobal: 0
  # 过期时间(单位: 秒)
  expire: 30
  # 过期方式(TTL: 初始化过期(false); TTI: 最后一次访问过期(true))
  last: true
  # memcached缓存配置
  memcached:
    # 地址
    host: 127.0.0.1
    # 端口
    port: 8000
    # 用户名
    username: memcached
    # 密码
    password: 123456
    # 超时时间
    timeout: 1000
  # redis缓存配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口
    port: 9000

# 文件配置
# 默认取配置文件中配置, 如果配置文件不存在取数据库中的配置
file:
  # 是否保持原文件名称
  # 保持文件名(有可能被覆盖)
  # 不保持(文件名规则: 当前时间+32位uuid+后缀名)
  keepName: true
  # 文件类型 local(默认, 本地), oss(阿里云OSS), qiniu(七牛云), upyun(又拍云)
  type: local

  # OSS
  oss:
    # endPoint
    endPoint: http://oss-cn-beijing.aliyuncs.com
    # accessKeyId
    accessKeyId: LTAI6VjozfHgydxx
    # accessKeySecret
    accessKeySecret: K8qsqXsOfsCOtoViE9bXge1pRk8q5q
    # bucket名称
    bucketName: codframe
    # 最大连接数
    maxConnections: 200
    # 请求超时时间, 默认50s
    socketTimeout: 10000
    # 失败重试次数, 默认3次
    maxErrorRetry: 3
    projectName: hitu-12306-validate
    headUrl: https://hitu-12306-validate.oss-cn-beijing.aliyuncs.com/

  # 本地
  local:
    path: ./attachment/

  # 七牛
  qiniu:
    key: key
    value: value

  # 又拍云
  upyun:
    key: key
    value: value





